// API Requests
export const FETCH_MEALS_REQUEST = 'FETCH_MEALS_REQUEST';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE';

export const FETCH_REC_REQUEST = 'FETCH_REC_REQUEST';
export const FETCH_REC_SUCCESS = 'FETCH_REC_SUCCESS';
export const FETCH_REC_FAILURE = 'FETCH_REC_FAILURE';

export const CLEAN_DATA_STATE = 'CLEAN_DATA_STATE';
